language: java

jdk:
  - oraclejdk8

env:
  global:
    - OTN_USER="oracle_shit_r193jfs89duf@mailinator.com"
    - OTN_PASSWORD="Oracle123"

# We first install the maven oracle-resource-maven-plugin in order to install Oracle artifact in our repository
before_install:
  - wget "https://github.com/radium226/otn/archive/master.zip" -O "master.zip"
  - unzip "master.zip"
  - cd "otn-master"
  - mvn install
  - cd ".."
  - rm -Rf "otn-master"
  
install: mvn --settings ./settings.xml install -DskipTests
#bouya
